CREATE DATABASE IF NOT EXISTS rede_academias ;

USE rede_academias;

CREATE TABLE IF NOT EXISTS unidade (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
endereco VARCHAR(45) NOT NULL,
telefone VARCHAR(15) NOT NULL, 
id_aluno INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (id_aluno) REFERENCES alunos(id) ); 

CREATE TABLE IF NOT EXISTS alunos (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
endereco VARCHAR(45) NOT NULL,
telefone VARCHAR(15) NOT NULL, 
id_plano INT NOT NULL,
id_acesso INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (id_plano) REFERENCES plano(id) ,
FOREIGN KEY (id_acesso) REFERENCES acesso(id) );

CREATE TABLE IF NOT EXISTS plano (
id INT NOT NULL AUTO_INCREMENT,
tipo_plano VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS acesso (
id INT NOT NULL AUTO_INCREMENT,
tipo_acesso VARCHAR(15) NOT NULL, 
id_aluno INT NOT NULL,
PRIMARY KEY(id)
 );